# Camera
USE_CAMERA_STUB := true

# Camera flags
BOARD_GLOBAL_CFLAGS += -DCAMERA_VENDOR_L_COMPAT
TARGET_CAMERASERVICE_CLOSES_NATIVE_HANDLES := true

# Legacy HAL
# TARGET_HAS_LEGACY_CAMERA_HAL1 := true
